language: ruby
rvm:
- 2.7.0
before_install:
- gem update --system
- gem install bundler
- gem install aws-sdk-lambda
- gem install aws-sdk-cloudwatchevents
install:
- rake run_bundler
script:
- rake test
deploy:
- provider: lambda
  function_name: SierraHoldingUpdatePoller-dev
  description: A service for polling the Sierra API for updates from the Holdings
    endpoint
  region: us-east-1
  role: arn:aws:iam::224280085904:role/lambda_basic_execution
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  environment:
    variables:
      LOG_LEVEL: debug
      S3_AWS_REGION: us-east-1
      NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
      PLATFORM_API_BASE_URL: https://dev-platform.nypl.org/api/v0.1
      BUCKET_NAME: sierra-poller-state-dev
      SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
      SIERRA_VERSION: v6
      SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v3/token
      SIERRA_OAUTH_ID: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQEPfTm0ZNPHAtRD1am3KPF8AAAAejB4BgkqhkiG9w0BBwagazBpAgEAMGQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCSeDlLbDCkrUw5HgAgEQgDe3aLUovzs4zQKOR/+UQXEOWF98UvjAvPijVSi2WlVme+6gvCDAj/Eicp26/VsAbxc2OhdMazUZ
      SIERRA_OAUTH_SECRET: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQGkTFrDp4UWdX4YCT2TX8iyAAAAcjBwBgkqhkiG9w0BBwagYzBhAgEAMFwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMT5TuObnrfHCIbSk8AgEQgC8k9u2afElzRHRs+pPxjPsRGjPIrWQBD9VUssj3rE1IlRz4kF3FM8jc/GAyFKFsMA==
      RECORD_TYPE: holdings
      RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
      SCHEMA_TYPE: SierraHolding
      KINESIS_STREAM: SierraHoldingParser-dev
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  on:
    branch: development
- provider: lambda
  function_name: SierraHoldingUpdatePoller-qa
  description: A service for polling the Sierra API for updates from the Holdings
    endpoint
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  environment:
    variables:
      LOG_LEVEL: debug
      S3_AWS_REGION: us-east-1
      NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
      PLATFORM_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1
      BUCKET_NAME: sierra-poller-state-qa
      SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
      SIERRA_VERSION: v6
      SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v3/token
      SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA6yJkJXvJKEQUcsCAIBEIA3oerpjzhASuO2ZGudbLoo3dCqgPJfcRu2fj1x2an58I9ldyKNArEv5rzJFYasX3FOrnMeqHdYAA==
      SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLQgrst3U3mqh14f/QIBEIAvR0AVyVvE/sYzsJV2rzFuBslo6xa1nV97F/furZ0V7s7/vZcMQ9gRN1N3B21wDp8=
      RECORD_TYPE: holdings
      RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
      SCHEMA_TYPE: SierraHolding
      KINESIS_STREAM: SierraHoldingParser-qa
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
- provider: lambda
  function_name: SierraHoldingUpdatePoller-production
  description: A service for polling the Sierra API for updates from the Holdings
    endpoint
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  event:
    SCHEDULE_EXPRESSION: rate(15 minutes)
  environment:
    variables:
      LOG_LEVEL: debug
      S3_AWS_REGION: us-east-1
      NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
      PLATFORM_API_BASE_URL: https://platform.nypl.org/api/v0.1
      BUCKET_NAME: sierra-poller-state-production
      SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
      SIERRA_VERSION: v6
      SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v3/token
      SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA6yJkJXvJKEQUcsCAIBEIA3oerpjzhASuO2ZGudbLoo3dCqgPJfcRu2fj1x2an58I9ldyKNArEv5rzJFYasX3FOrnMeqHdYAA==
      SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLQgrst3U3mqh14f/QIBEIAvR0AVyVvE/sYzsJV2rzFuBslo6xa1nV97F/furZ0V7s7/vZcMQ9gRN1N3B21wDp8=
      RECORD_TYPE: holdings
      RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
      SCHEMA_TYPE: SierraHolding
      KINESIS_STREAM: SierraHoldingParser-production
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  on:
    branch: main
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: STHw6LScNfsamAXARJBd8r5Rs+yE8hEePWSL6EmBwxeo/3JJiLNk50iyQGGWWWpiXWFvkgLsYK5qEgl+UCheiWIlDUelTRkjliDCS8Ut3q41d886Q3X7XW2XSqcz/RQKR1hlHt4mPmdyeUZ7VMy997+mkYSGgT36hlFeojLht2ZEDQRuPIyWHEM8uLlgCFlsvpg03MTHhf+ijTTv7Sq1G1jYpnRoikVtsUAE0qsJZg25DjUC49bVvxGGbKDqNyc7AtJtm3KoOdMbBs8IBjf8XJNgThjACwtDbO/sVNXkPpFkDfc9sCH+ihvzXDP95v9+LJR0BLV/S+YkXfMKdG5P6+VbKg1mng+LoL91L4HdT4A4FlVVTSHTSbgBDpY46pAheSpaktXYIHJ5xqhX1sJoIDFOQJKmT4+JqmNvgrnoUqYJGw2z1fM1DZV+inO9HG0K3or7/NCUAUaOTszt62OUkB4izIBbkx2wsN+qHuZMfI1/6F6yQ1cBBg4wgIi+fE7GYK6wxlt6GyyFStXG3lmEtYO1HNFSl377V1GBXESTTATxLGDJTM4wJk6g/bhGetXJUIVEWTfdHgIjuHlZuspCy4a3W3qT4xm2XJ+ShOOSgaaT+YSwyFPmMPZFqdD4Tr3Y0n41aw7lwu/gydsqm6rz3W2VMqEwycF2q2gI0lumC9Y=
  - secure: GW49G5hKs/0y8OAAyx/e/rUYkH9VBVj+rIad1N/rhx/fcKrZPwiooDhCjTbA0mvSBXkGDiMMqB9HsxkIEr+IX2m4RPXLnQwIulP5XIJIu0OVcED6xrRf6RLaFnlXbvArFxNFec1LOQY0Qg8RS/E0wlzhBN4IKGVbcYDEboB10LAxQ70Iathf5wSV9HRdv0eBkdCZKgPG5KLgddKcLBmTRurdNWW3P4KKV5QhofbrveqM8UNvjWkvrHTAknDB2qWB3DZ/Bpix79Yup9zJP4E2xvHSMJ5AXyLbur7dj3oHS4rFt2z+jQeaLg0yAOsFVQkj/dz9T6V0skwk08KqnysnI652ERYEuYtcrc+SATT3fDDobPPdODjI8zTR6JpCJGTO4NmgpH68Zsqu0OOCi7pWTzTpaGRybpI+OT8uc9O5QtAy15HQ4XrfvAA/iPAU6cMS4BYCAq1VFeTFNcsKIXQqqfAbfzoEG+FE+QG3aXUGxLdyX1dLNxdTW8E6lWRre2SZnWtluwInB72yFZb4DRwRCIXZz2hPwvUf1GgWDPpN4OplhFU1SJZ/V3bcptSqF9h9Tn3IxEmkD17KshbEzKdwD8vHGr0u6xhdbXxEmkaJFdvT30C74Lkwnt0qtDU/21hhHbs6IyoNeuB+l82SXQG3D9vvkJ1z4XMTGdD7bS+DdOs=
  - secure: aBbfEGrbky8BFDcHWgBg9KC/i07ps6m1u6lDBpEC28qcrDHB+5vqaAPJXVXQwM5k7q+mJlR8dDtDewQksDKfnmt34EbalwN3PQCLT7wulnq7DpZwCXNcm/RLMCR7DSaYPfrDQ6B28We0xvH2N9sNBKc4+MN+3M9ZT1QftRHGKZvGpiQq3nVuWWUgR27dktdnClvoKFk3JccMfT3492MEVdD+YzxAuhnGQxjAHRFXHgu9n72mStSmIZvTYIbUqtQ6ngJIF67lfKxPnZ6aNNTXFn1thq1NN2E+vFHaRTFiCJXg495JKikH3+a7Ovb7E0oL68MZqplajCi6jLmbgo0iPsMqU9XTV2QWo5OuHtqfXC/MnELa8peqwPsop1FPz5EFh6T7tUG740IayKSOpbGAHu/bLqPYQ+o/6yIbLJoA5oInAuiGPpOuaBueCO8f1eYoQt4onTyeb1topS+YBdUs+OStXEazbzTYql6xM6oEUY7nU6iDtRJMpbVROVdINufQl1EBnz98iXSMxXluCpZTgD0Z7a0gDiRxHtg0hWn2h2irg/nGuhX5ZvZ6h5Sdcvj8uFRZHuBH1pKQ/0NT3YSYC28j/yKPi+K5kBxBWITXElvMDRlGSslOlvXNlBS7luAYwJVy8hWBDlw/ybXa8kgdygkXjBspmqQEDdRMvhkDipM=
