language: ruby
rvm:
  - 2.7.0
before_install:
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip
  - gem update --system
  - gem install bundler
  - gem install aws-sdk-lambda
  - gem install aws-sdk-cloudwatchevents
install:
  - rake run_bundler
jobs:
  include:
    - stage: test
      script:
      - rake test
    - stage: deploy qa
      if: type IN (push) and branch = qa
      env:
      # where do these come from???
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_QA
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_QA
      script:
        - rm -rf vendor
        - bundle install --without test
        - terraform -chdir=provisioning/qa init -input=false
        - echo "Deploying to qa"
        - terraform -chdir=provisioning/qa apply -auto-approve -input=false
    - stage: deploy production
      if: type IN (push) and branch = main
      env:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
      script:
        - rm -rf vendor
        - bundle install --without test
        - terraform -chdir=provisioning/production init -input=false
        - echo "Deploying to production"
        - terraform -chdir=provisioning/production apply -auto-approve -input=false

# what are these
env:
  global:
  - secure: mvkAvo1cMLYQ8cFc/Jm7EBYOQ2kXGJnc/8D9PmHsQuktZcvzGSZe8yM9RCkzakyXQyf8XYmlT73/SwLx/l8g4X0Bg+9YfNSxkyl0mMfPXCbfe86/LQim+ZEiCaXn40PVtv+rOqeh9Ux2YJgLRRrE3mp7sTEcqKEp3mMlgMExSr0Wurlxwp5enEy2e9beO4n2QLzDsVL1yTEavdYgko/9eelc0jd+ShH2O9XUra/Uhkq3QoOWHTrp44AUzH8YTo637Ta75h4QNmMjoMqZH3bw6I+nUR8yTy8gOJEI2wKg2Uv9HriPYeW77WZQhLN0v/4Yo/r8LOjwbCWTCxs1WDMF/sfIPMSv+/gIYTk3/jkLrg7+ikgBfzYleoKF4dyax7fNgRA9Kure3hTXnnVBaeSqLu8x8v9eDRj9Q2VLb2maia0Fooa3zwOfbH9m3setKqRt7ksurzyQ3F7UXKRq6VmHrDQnLiDRzdjxjjq0ML2eDR4k9WQt9cl+EaCMEUtWelQtOjYIcSAFIUI3A6LMqop3om0e/ibl5YNdr3m4uibF9CQjBQb+BzkUZsrJA65ZtGlPIcIQSgI2J3dJWl+h4vhVSX8pvEqt0KkRSlw3J4wYtxbxMgt9Amx8uAFfwuMlvZBS3Jf7VQNh2MLqR8PdbEgzJVxUKG3T3CnW4ltrCuxwnCw=
  - secure: jYBtN1M3AATumSeq+FKbAsYetV2RclyK/itSUc9oMpgpJwnyWcxi+kPZhlbyqQjdHWTBPL6xVnxPtBDR6w2Rf0JwCBBBpNnJpBoEaTrgBWKU2BwjEc0Og+yxoXyOVKsG7R3uuQHjKZuHcnTTYYctzroPpTng5JxHLZ+nOw52UY8RK3Xv/539MNh+UxiEk8mn6af2fdhOeD0EFWA4BrfOh99YXdPdZBVq/jOkDnvIGS8leHR7AbB126gKoWyVG51Q/vZ8eX0oojGGxMw200kdljzEUCKIB0b2djVHhVjy0a4Plh34wfE/dokJ3C96u/CQnn22LxDC8wJl5aTjGQpY+hcNMomW7YzcwSN1+QPg1MszLMXGtfcJ3s6jDcIoyZunosY+TYZo5Wp8vLjNJharI0Wlt+y33A8uiMuG785VAjsHS8M8pKeyQIUrCkuSYjUpyR1D9iumtJwYgrAbA997paoPUO9l0f1wBBnexWmyFbZhVkQR2bA5gaL5AnuevhLEP21s3q6yNUYrmSrMW+q7/x5xtAr7jc446I/dxoCqZ6K//XNGQKdWRFEwu7Vb++hr3TlW2bUoOGk8qzKCpv20JguGHNAfNzpnWjCq/PHJnWshwGFG8FdxVEtztiow5taZN2GFvouXtGfyqWCJXk7uP/Gd8BE1hH5s//51Wr6sMps=
  - secure: YGm0GNfhRuOJuE1g7SxMQeqGYtWmf5gJCdtneNKBWkX+HRD4ViY9IuJy45t1guOYPromDO520EDi34dRF0u/PEjmP15UaDBjpqM1hO4H93C2yIpV6lpUeiGHRYHPTlVSs+iCaijGGpsyUGYgZH0ebXWGPTMHY4Oayf7MujOmWqJC8ydql7WEIyPS7QBnDTOWnjwvmqDrVNHwB/TyzOn+ktK4gIaA/PIxdt59jXQ61NzyfrZg9sF0ParXKWyykBNqrwgTbngQPRr3vx1PT8ZVfXfFXbb9Oo1gpQhqqNrNUIFY+V6JiONtIx6JCuxGcUs6/fmwual9/8F6zws5O7o9zP+WptGNacN3iVafbjjeQ8BbwSq1XBR7vPp2mRhuu+7q/Ak96ovx0OvFhK8er/xyJvtcwfUWiGmRC0pJSJnqIqgzXPyKNqEmzy+RYQxMo7MwTfvPrcLmFLOm5tFxMRQkZWfD8Oi/EHr7auafT1V5Gc0qwmXpK1flSqTCI6cyJVeH7ig7qBPMvEGrmTO9sVi8klFE+r/yxaMwBa4CtEhdhWwlDYch753TGPb8dv1o8PPixwzzZUjKg8dFObyoVzkwgAcb3LSFvZ7CJzqpVVU2K1oMvJhJ6h3ls1uKDhEchADuysT8U9j14xDdFFKlEJfrPX1a0lQCxreEE1HWhsoX5d0=
  - TF_VERSION=1.0.11

    # deploy:
    #   - provider: lambda
    #     function_name: SierraHoldingUpdatePoller-dev
    #     description:
    #       A service for polling the Sierra API for updates from the Holdings
    #       endpoint
    #     region: us-east-1
    #     role: arn:aws:iam::224280085904:role/lambda_basic_execution
    #     runtime: ruby2.7
    #     timeout: 60
    #     module_name: app
    #     handler_name: handle_event
    #     event:
    #       schedule_expression: rate(1 hour)
    #     environment:
    #       variables:
    #         LOG_LEVEL: debug
    #         S3_AWS_REGION: us-east-1
    #         NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
    #         PLATFORM_API_BASE_URL: https://dev-platform.nypl.org/api/v0.1/
    #         BUCKET_NAME: sierra-poller-state-dev
    #         SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
    #         SIERRA_VERSION: v6
    #         SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v3/token
    #         SIERRA_OAUTH_ID: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQEPfTm0ZNPHAtRD1am3KPF8AAAAejB4BgkqhkiG9w0BBwagazBpAgEAMGQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCSeDlLbDCkrUw5HgAgEQgDe3aLUovzs4zQKOR/+UQXEOWF98UvjAvPijVSi2WlVme+6gvCDAj/Eicp26/VsAbxc2OhdMazUZ
    #         SIERRA_OAUTH_SECRET: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQGkTFrDp4UWdX4YCT2TX8iyAAAAcjBwBgkqhkiG9w0BBwagYzBhAgEAMFwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMT5TuObnrfHCIbSk8AgEQgC8k9u2afElzRHRs+pPxjPsRGjPIrWQBD9VUssj3rE1IlRz4kF3FM8jc/GAyFKFsMA==
    #         RECORD_TYPE: holdings
    #         RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
    #         SCHEMA_TYPE: SierraHolding
    #         KINESIS_STREAM: SierraHoldingParser-dev
    #     access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
    #     secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
    #     on:
    #       branch: development
    #   - provider: lambda
    #     function_name: SierraHoldingUpdatePoller-qa
    #     description:
    #       A service for polling the Sierra API for updates from the Holdings
    #       endpoint
    #     region: us-east-1
    #     role: arn:aws:iam::946183545209:role/lambda-full-access
    #     runtime: ruby2.7
    #     timeout: 60
    #     module_name: app
    #     handler_name: handle_event
    #     event:
    #       schedule_expression: rate(1 hour)
    #     environment:
    #       variables:
    #         LOG_LEVEL: debug
    #         S3_AWS_REGION: us-east-1
    #         NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
    #         PLATFORM_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
    #         BUCKET_NAME: sierra-poller-state-qa
    #         SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
    #         SIERRA_VERSION: v6
    #         SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v3/token
    #         SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA6yJkJXvJKEQUcsCAIBEIA3oerpjzhASuO2ZGudbLoo3dCqgPJfcRu2fj1x2an58I9ldyKNArEv5rzJFYasX3FOrnMeqHdYAA==
    #         SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLQgrst3U3mqh14f/QIBEIAvR0AVyVvE/sYzsJV2rzFuBslo6xa1nV97F/furZ0V7s7/vZcMQ9gRN1N3B21wDp8=
    #         RECORD_TYPE: holdings
    #         RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
    #         SCHEMA_TYPE: SierraHolding
    #         KINESIS_STREAM: SierraHoldingParser-qa
    #     access_key_id: "$AWS_ACCESS_KEY_ID_QA"
    #     secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
    #     on:
    #       branch: qa


    #   - provider: lambda
    #     function_name: SierraBibUpdatePoller-qa
    #     event:
    #       schedule_expression: rate(5 minutes)
    #     on:
    #       branch: qa




    #   - provider: lambda
    #     function_name: SierraItemUpdatePoller-qa
    #     description:
    #       A service for polling the Sierra API for updates from the Items
    #       endpoint
    #     region: us-east-1
    #     role: arn:aws:iam::946183545209:role/lambda-full-access
    #     runtime: ruby2.7
    #     timeout: 60
    #     module_name: app
    #     handler_name: handle_event
    #     event:
    #       schedule_expression: rate(5 minutes)
    #     environment:
    #       variables:
    #         LOG_LEVEL: debug
    #         S3_AWS_REGION: us-east-1
    #         NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
    #         PLATFORM_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
    #         BUCKET_NAME: sierra-poller-state-qa
    #         SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
    #         SIERRA_VERSION: v6
    #         SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v3/token
    #         SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA6yJkJXvJKEQUcsCAIBEIA3oerpjzhASuO2ZGudbLoo3dCqgPJfcRu2fj1x2an58I9ldyKNArEv5rzJFYasX3FOrnMeqHdYAA==
    #         SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLQgrst3U3mqh14f/QIBEIAvR0AVyVvE/sYzsJV2rzFuBslo6xa1nV97F/furZ0V7s7/vZcMQ9gRN1N3B21wDp8=
    #         RECORD_TYPE: items
    #         RECORD_FIELDS: default,fixedFields,varFields
    #         SCHEMA_TYPE: ItemPostRequest
    #         KINESIS_STREAM: ItemPostRequest-qa
    #     access_key_id: "$AWS_ACCESS_KEY_ID_QA"
    #     secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
    #     on:
    #       branch: qa
    #   - provider: lambda
    #     function_name: SierraHoldingUpdatePoller-production
    #     description:
    #       A service for polling the Sierra API for updates from the Holdings
    #       endpoint
    #     region: us-east-1
    #     role: arn:aws:iam::946183545209:role/lambda-full-access
    #     runtime: ruby2.7
    #     timeout: 60
    #     module_name: app
    #     handler_name: handle_event
    #     event:
    #       schedule_expression: rate(15 minutes)
    #     vpc_config:
    #       subnet_ids:
    #         - subnet-59bcdd03
    #         - subnet-5deecd15
    #       security_group_ids:
    #         - sg-116eeb60
    #     environment:
    #       variables:
    #         LOG_LEVEL: debug
    #         S3_AWS_REGION: us-east-1
    #         NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
    #         PLATFORM_API_BASE_URL: https://platform.nypl.org/api/v0.1/
    #         BUCKET_NAME: sierra-poller-state-production
    #         SIERRA_API_BASE_URL: https://ilsstaff.nypl.org:443/iii/sierra-api
    #         SIERRA_OAUTH_URL: https://ilsstaff.nypl.org:443/iii/sierra-api/v3/token
    #         SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKwPp4FB9Xx0spVyFwIBEIA34CUI1a5kKePBaRIJ2Wou+KDvCmrh+tDyOSiBbIb3zXo2sbj2UGfwKCdlF2GB0p/UnmQ2ilPwgw==
    #         SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIMwgYAGCSqGSIb3DQEHBqBzMHECAQAwbAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwM8xL3gQb/QIsIWykCARCAP7hsMLN/VeEhZrHsYKQkkdCycujr8Wg5X8zLsrRddPT02UhBGfKWTn10xOIarqUAnu6buZWv6ns2g+pAVtvfWw==
    #         SIERRA_VERSION: v6
    #         RECORD_TYPE: holdings
    #         RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
    #         SCHEMA_TYPE: SierraHolding
    #         KINESIS_STREAM: SierraHoldingParser-production
    #     access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    #     secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    #     on:
    #       branch: main
    #   - provider: lambda
    #     function_name: SierraBibUpdatePoller-production
    #     description:
    #       A service for polling the Sierra API for updates from the Bibs
    #       endpoint
    #     region: us-east-1
    #     role: arn:aws:iam::946183545209:role/lambda-full-access
    #     runtime: ruby2.7
    #     timeout: 60
    #     module_name: app
    #     handler_name: handle_event
    #     event:
    #       schedule_expression: rate(1 minute)
    #     vpc_config:
    #       subnet_ids:
    #         - subnet-59bcdd03
    #         - subnet-5deecd15
    #       security_group_ids:
    #         - sg-116eeb60
    #     environment:
    #       variables:
    #         LOG_LEVEL: debug
    #         S3_AWS_REGION: us-east-1
    #         NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
    #         PLATFORM_API_BASE_URL: https://platform.nypl.org/api/v0.1/
    #         BUCKET_NAME: sierra-poller-state-production
    #         SIERRA_API_BASE_URL: https://ilsstaff.nypl.org:443/iii/sierra-api
    #         SIERRA_OAUTH_URL: https://ilsstaff.nypl.org:443/iii/sierra-api/v3/token
    #         SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKwPp4FB9Xx0spVyFwIBEIA34CUI1a5kKePBaRIJ2Wou+KDvCmrh+tDyOSiBbIb3zXo2sbj2UGfwKCdlF2GB0p/UnmQ2ilPwgw==
    #         SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIMwgYAGCSqGSIb3DQEHBqBzMHECAQAwbAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwM8xL3gQb/QIsIWykCARCAP7hsMLN/VeEhZrHsYKQkkdCycujr8Wg5X8zLsrRddPT02UhBGfKWTn10xOIarqUAnu6buZWv6ns2g+pAVtvfWw==
    #         SIERRA_VERSION: v6
    #         RECORD_TYPE: bibs
    #         RECORD_FIELDS: default,fixedFields,varFields,normTitle,normAuthor,orders,locations
    #         SCHEMA_TYPE: BibPostRequest
    #         KINESIS_STREAM: BibPostRequest-production
    #     access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    #     secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    #     on:
    #       branch: main
    #   - provider: lambda
    #     function_name: SierraItemUpdatePoller-production
    #     description:
    #       A service for polling the Sierra API for updates from the Items
    #       endpoint
    #     region: us-east-1
    #     role: arn:aws:iam::946183545209:role/lambda-full-access
    #     runtime: ruby2.7
    #     timeout: 60
    #     module_name: app
    #     handler_name: handle_event
    #     event:
    #       schedule_expression: rate(1 minute)
    #     vpc_config:
    #       subnet_ids:
    #         - subnet-59bcdd03
    #         - subnet-5deecd15
    #       security_group_ids:
    #         - sg-116eeb60
    #     environment:
    #       variables:
    #         LOG_LEVEL: debug
    #         S3_AWS_REGION: us-east-1
    #         NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
    #         PLATFORM_API_BASE_URL: https://platform.nypl.org/api/v0.1/
    #         BUCKET_NAME: sierra-poller-state-production
    #         SIERRA_API_BASE_URL: https://ilsstaff.nypl.org:443/iii/sierra-api
    #         SIERRA_OAUTH_URL: https://ilsstaff.nypl.org:443/iii/sierra-api/v3/token
    #         SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKwPp4FB9Xx0spVyFwIBEIA34CUI1a5kKePBaRIJ2Wou+KDvCmrh+tDyOSiBbIb3zXo2sbj2UGfwKCdlF2GB0p/UnmQ2ilPwgw==
    #         SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIMwgYAGCSqGSIb3DQEHBqBzMHECAQAwbAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwM8xL3gQb/QIsIWykCARCAP7hsMLN/VeEhZrHsYKQkkdCycujr8Wg5X8zLsrRddPT02UhBGfKWTn10xOIarqUAnu6buZWv6ns2g+pAVtvfWw==
    #         SIERRA_VERSION: v6
    #         RECORD_TYPE: items
    #         RECORD_FIELDS: default,fixedFields,varFields
    #         SCHEMA_TYPE: ItemPostRequest
    #         KINESIS_STREAM: ItemPostRequest-production
    #     access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    #     secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    #     on:
    #       branch: main
    # after_deploy:
    #   - rake set_config
    # notifications:
    #   email:
    #     on_failure: always
    # env:
    #   global:
    #     - secure: STHw6LScNfsamAXARJBd8r5Rs+yE8hEePWSL6EmBwxeo/3JJiLNk50iyQGGWWWpiXWFvkgLsYK5qEgl+UCheiWIlDUelTRkjliDCS8Ut3q41d886Q3X7XW2XSqcz/RQKR1hlHt4mPmdyeUZ7VMy997+mkYSGgT36hlFeojLht2ZEDQRuPIyWHEM8uLlgCFlsvpg03MTHhf+ijTTv7Sq1G1jYpnRoikVtsUAE0qsJZg25DjUC49bVvxGGbKDqNyc7AtJtm3KoOdMbBs8IBjf8XJNgThjACwtDbO/sVNXkPpFkDfc9sCH+ihvzXDP95v9+LJR0BLV/S+YkXfMKdG5P6+VbKg1mng+LoL91L4HdT4A4FlVVTSHTSbgBDpY46pAheSpaktXYIHJ5xqhX1sJoIDFOQJKmT4+JqmNvgrnoUqYJGw2z1fM1DZV+inO9HG0K3or7/NCUAUaOTszt62OUkB4izIBbkx2wsN+qHuZMfI1/6F6yQ1cBBg4wgIi+fE7GYK6wxlt6GyyFStXG3lmEtYO1HNFSl377V1GBXESTTATxLGDJTM4wJk6g/bhGetXJUIVEWTfdHgIjuHlZuspCy4a3W3qT4xm2XJ+ShOOSgaaT+YSwyFPmMPZFqdD4Tr3Y0n41aw7lwu/gydsqm6rz3W2VMqEwycF2q2gI0lumC9Y=
    #     - secure: GW49G5hKs/0y8OAAyx/e/rUYkH9VBVj+rIad1N/rhx/fcKrZPwiooDhCjTbA0mvSBXkGDiMMqB9HsxkIEr+IX2m4RPXLnQwIulP5XIJIu0OVcED6xrRf6RLaFnlXbvArFxNFec1LOQY0Qg8RS/E0wlzhBN4IKGVbcYDEboB10LAxQ70Iathf5wSV9HRdv0eBkdCZKgPG5KLgddKcLBmTRurdNWW3P4KKV5QhofbrveqM8UNvjWkvrHTAknDB2qWB3DZ/Bpix79Yup9zJP4E2xvHSMJ5AXyLbur7dj3oHS4rFt2z+jQeaLg0yAOsFVQkj/dz9T6V0skwk08KqnysnI652ERYEuYtcrc+SATT3fDDobPPdODjI8zTR6JpCJGTO4NmgpH68Zsqu0OOCi7pWTzTpaGRybpI+OT8uc9O5QtAy15HQ4XrfvAA/iPAU6cMS4BYCAq1VFeTFNcsKIXQqqfAbfzoEG+FE+QG3aXUGxLdyX1dLNxdTW8E6lWRre2SZnWtluwInB72yFZb4DRwRCIXZz2hPwvUf1GgWDPpN4OplhFU1SJZ/V3bcptSqF9h9Tn3IxEmkD17KshbEzKdwD8vHGr0u6xhdbXxEmkaJFdvT30C74Lkwnt0qtDU/21hhHbs6IyoNeuB+l82SXQG3D9vvkJ1z4XMTGdD7bS+DdOs=
    #     - secure: aBbfEGrbky8BFDcHWgBg9KC/i07ps6m1u6lDBpEC28qcrDHB+5vqaAPJXVXQwM5k7q+mJlR8dDtDewQksDKfnmt34EbalwN3PQCLT7wulnq7DpZwCXNcm/RLMCR7DSaYPfrDQ6B28We0xvH2N9sNBKc4+MN+3M9ZT1QftRHGKZvGpiQq3nVuWWUgR27dktdnClvoKFk3JccMfT3492MEVdD+YzxAuhnGQxjAHRFXHgu9n72mStSmIZvTYIbUqtQ6ngJIF67lfKxPnZ6aNNTXFn1thq1NN2E+vFHaRTFiCJXg495JKikH3+a7Ovb7E0oL68MZqplajCi6jLmbgo0iPsMqU9XTV2QWo5OuHtqfXC/MnELa8peqwPsop1FPz5EFh6T7tUG740IayKSOpbGAHu/bLqPYQ+o/6yIbLJoA5oInAuiGPpOuaBueCO8f1eYoQt4onTyeb1topS+YBdUs+OStXEazbzTYql6xM6oEUY7nU6iDtRJMpbVROVdINufQl1EBnz98iXSMxXluCpZTgD0Z7a0gDiRxHtg0hWn2h2irg/nGuhX5ZvZ6h5Sdcvj8uFRZHuBH1pKQ/0NT3YSYC28j/yKPi+K5kBxBWITXElvMDRlGSslOlvXNlBS7luAYwJVy8hWBDlw/ybXa8kgdygkXjBspmqQEDdRMvhkDipM=
