language: ruby
rvm:
- 2.7.0
before_install:
- wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
- unzip terraform_"$TF_VERSION"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$TF_VERSION"_linux_amd64.zip
- gem update --system
- gem install bundler
- gem install aws-sdk-lambda
- gem install aws-sdk-cloudwatchevents
install:
- rake run_bundler
jobs:
  include:
  - stage: test
    script:
    - rake test
  - stage: deploy qa
    if: type IN (push) and branch = qa
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_QA
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_QA
    script:
    - rm -rf vendor
    - bundle install --without test
    - terraform -chdir=provisioning/qa init -input=false
    - echo "Deploying to qa"
    - terraform -chdir=provisioning/qa apply -auto-approve -input=false
  - stage: deploy production
    if: type IN (push) and branch = main
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
    script:
    - rm -rf vendor
    - bundle install --without test
    - terraform -chdir=provisioning/production init -input=false
    - echo "Deploying to production"
    - terraform -chdir=provisioning/production apply -auto-approve -input=false
    
env:
  global:
  - secure: hHT2Izw7/6oBvuXm9d53/MOnHAHdwQUDMx0k6rjP8JCm7vJdqWVoq0ocCMD2AVZWl5EO4PTwJnV5Z8dj8d9r+2DjlGtDzbCDEoYJSaoCt1KVC9RqoG1KYQEsPpGZjgdoq0AlURWgWPemL5ltYYsHRnHC8Q1UeZu7rN62QVEC1eU3ot2verhU5uJYsYJgGkyfLOOLYkqpCdN1eCG5/ccyj4KbjSTr/chICGtPDYQ0hthoO01bkP6O1bQMtnjyIVnKL/uV3mfJlpZG/1ZoK7NkNTHj1nDu1A1I4nEus2NU0kftSVROOhDVl2QQOoPLSvaCD1fOkkEku+m9fNJvKMbBGGwqQxLbOFRpVG7d5DbRvKdQYfbuoOqM5ogckl4AdVVT9054NX8Y9IvgCuHvpQ/+sm6XHUUmP/QLGr/f48bdERzJS7VX+amgSkb1GRV0cOz+8EWwy3uMHA1z24ey7Jr4MOsK5wq7IPObV/2d7ZXjjrOJr+GkThJewElr/6Vas8/SEXB+WZHu3OWH6Uy53ZAh6CX1ChbXTNekH0qyvj9Cd1ST8HUoxWfO0S5rigS4aTwH1bdz+/uFoxZyYyggQzaJ8SnpqQn/JeRxJDBlNaDdkvt8FLSeEPKx+KZOewxtqzCEmhT/C4SLPgwRJa8UbjXuAcWtFoYo/UScluF/5xdGfUg=
  - secure: e2AkWul5Kb7IZaGFNt/RksnvfRgOmarfpGiYwoAoc7q+l7bHkKnvhdyG6x43J5cQ985LNOeBrK7q74J169lxeulNrtL0pbR1XsIKdrhyAx0EeblFmdlkW7ttIlCT729FLqLE3+rxreRSHeFZ5DJ9co696m+G7OhwARzTsumUxzghnJu7ilAMXime7c8oJJVer3Wj2TQV871LhvGUkIPiBvxK9CIxgxoLCLGzcE94XDgJHmMFu6BxG7y4Qh6Uz1Bxpp5MgWRYs9MazVv1XfvCwnXviLY3UBVdaY1dR2IAAJAYIjQcKzPUkfuIO0pA0UBXL/NzT+/9WB1o70vUq8UicObflSCPtdSgPMpz99rr6gcde/LIUiiyEeYzN+gkRMoI3hSlZpW58MCVqKof2RA3WRzKsij7dhXUew4nAhcww318BxoOb7PPAfQqfidafAqAHs8jp55JkTHYcCZ8su6PsJsS4xpLJlS9eX5TPAEdXOho8xbHlCxA7b17qdtsr66fCSNXUWyK8mtHGd8lz/u1J63OgNFPKk/mji/nc7JcgBTPbM+3xyLm7ZjknpeeTOROYyuNNuxaiYH0aouGpjyShk6ns2P9Lp42I6cTRm0PP2fuA2kCtACl8cNdBtvzMdzSQqUCi7adXtXlngC4BSfY5Y2S5KU/WWRHUh11gG155II=
  - TF_VERSION=1.0.11
