V1
language: ruby
rvm:
- 2.7.0
before_install:
- wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
- unzip terraform_"$TF_VERSION"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$TF_VERSION"_linux_amd64.zip
- gem update --system
- gem install bundler
- gem install aws-sdk-lambda
- gem install aws-sdk-cloudwatchevents
install:
- rake run_bundler
jobs:
  allow_failures:
    - rvm: 2.7.0
  include:
  - stage: test
    script:
    - rake test 
  - stages: 
    name: deploy qa
    if: type IN (push) and branch = qa
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_QA
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_QA
    script:
    - rm -rf vendor
    - rake run_bundler
  - script:
    - terraform -chdir=provisioning/qa/bib_update init -input=false
    - echo "Deploying Bib Update to qa"
    - terraform -chdir=provisioning/qa/bib_update apply -auto-approve -input=false
  - script:
    - terraform -chdir=provisioning/qa/bib_delete init -input=false
    - echo "Deploying Bib Delete to qa"
    - terraform -chdir=provisioning/qa/bib_delete apply -auto-approve -input=false
    
  - stage: deploy production
    if: type IN (push) and branch = main
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
    script:
    - rm -rf vendor
    - bundle config set deployment 'true'; bundle config; bundle install --without test
  - name: "Bib Update production"
    script:
    - terraform -chdir=provisioning/production/bib_update init -input=false
    - echo "Deploying Bib Update to production"
    - terraform -chdir=provisioning/production/bib_update apply -auto-approve -input=false
  - name: "Bib Delete production"
    script:
    - terraform -chdir=provisioning/production/bib_delete init -input=false
    - echo "Deploying Bib Delete to production"
    - terraform -chdir=provisioning/production/bib_delete apply -auto-approve -input=false

