AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Local configuration for the SierraUpdatePoller function'

Globals:
  Function:
    Timeout: 300
    Runtime: ruby2.7
    Handler: app.handle_event
    Environment:
      Variables:
        LOG_LEVEL: debug
        S3_AWS_REGION: us-east-1
        NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
        PLATFORM_API_BASE_URL: https://dev-platform.nypl.org/api/v0.1/
        BUCKET_NAME: sierra-poller-state-dev
        SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
        SIERRA_VERSION: v6
        SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v3/token
        SIERRA_OAUTH_ID: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQEPfTm0ZNPHAtRD1am3KPF8AAAAejB4BgkqhkiG9w0BBwagazBpAgEAMGQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCSeDlLbDCkrUw5HgAgEQgDe3aLUovzs4zQKOR/+UQXEOWF98UvjAvPijVSi2WlVme+6gvCDAj/Eicp26/VsAbxc2OhdMazUZ
        SIERRA_OAUTH_SECRET: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQGkTFrDp4UWdX4YCT2TX8iyAAAAcjBwBgkqhkiG9w0BBwagYzBhAgEAMFwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMT5TuObnrfHCIbSk8AgEQgC8k9u2afElzRHRs+pPxjPsRGjPIrWQBD9VUssj3rE1IlRz4kF3FM8jc/GAyFKFsMA==

Resources:
  SierraHoldingsUpdatePoller:
    Type: AWS::Serverless::Function
    Properties:
      # TODO Cloudwatch Event trigger here
      Environment:
        Variables:
          RECORD_TYPE: holdings
          RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
          SCHEMA_TYPE: SierraHolding
          KINESIS_STREAM: SierraHoldingParser-dev
