AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Local configuration for the SierraUpdatePoller function'

Globals:
  Function:
    Timeout: 300
    Runtime: ruby2.7
    Handler: app.handle_event
    Environment:
      Variables:
        LOG_LEVEL: debug
        S3_AWS_REGION: us-east-1
        NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
        PLATFORM_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
        BUCKET_NAME: sierra-poller-state-qa
        SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
        SIERRA_VERSION: v6
        SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v6/token
        SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJGDDlDYRAgm6Kq1CAIBEIA37Kuya0YgwuI3MPf83rCxeV75tN6Nh4pPGOIt5YInT+kdD89xTO3D/6B9OlK6T3+MWtymsJ+/Kg==
        SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKmT3cEELMoZ2huyrwIBEIAnibbT57jJuV6ah2iATkcglCYHhQze8aQ291egun6IOpv6NTAMJ4Hv
        BATCH_SIZE: 50
        RETRY_COUNT: 3
        RACK_ENV: development
Resources:
  SierraHoldingsUpdatePoller:
    Type: AWS::Serverless::Function
    Properties:
      # TODO Cloudwatch Event trigger here
      Environment:
        Variables:
          RECORD_TYPE: holdings
          RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
          SCHEMA_TYPE: SierraHolding
          KINESIS_STREAM: SierraHoldingParser-dev
  SierraItemUpdatePoller:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          KINESIS_STREAM: ItemPostRequest-qa
          RECORD_FIELDS: default,fixedFields,varFields
          RECORD_TYPE: items
          REQUEST_BATCH_SIZE: 200
          S3_KEY: ItemPostRequest
          SCHEMA_TYPE: ItemPostRequest
          SKIP_UPDATING_STATE_FILE: true
  SierraBibUpdatePoller:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          KINESIS_STREAM: BibPostRequest-qa
          RECORD_FIELDS: default,fixedFields,varFields,normTitle,normAuthor,orders,locations
          RECORD_TYPE: bibs
          REQUEST_BATCH_SIZE: 200
          S3_KEY: BibPostRequest
          SCHEMA_TYPE: BibPostRequest
          SKIP_UPDATING_STATE_FILE: true
