AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Local configuration for the SierraUpdatePoller function'

Globals:
  Function:
    Timeout: 300
    Runtime: ruby2.7
    Handler: app.handle_event
    Environment:
      Variables:
        LOG_LEVEL: debug
        S3_AWS_REGION: us-east-1
        NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
        PLATFORM_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
        BUCKET_NAME: sierra-poller-state-qa
        SIERRA_API_BASE_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api
        SIERRA_VERSION: v6
        SIERRA_OAUTH_URL: https://nypl-sierra-test.nypl.org:443/iii/sierra-api/v3/token
        SIERRA_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA6yJkJXvJKEQUcsCAIBEIA3oerpjzhASuO2ZGudbLoo3dCqgPJfcRu2fj1x2an58I9ldyKNArEv5rzJFYasX3FOrnMeqHdYAA==
        SIERRA_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLQgrst3U3mqh14f/QIBEIAvR0AVyVvE/sYzsJV2rzFuBslo6xa1nV97F/furZ0V7s7/vZcMQ9gRN1N3B21wDp8=
        BATCH_SIZE: 50

Resources:
  SierraHoldingUpdatePollerQA:
    Type: AWS::Serverless::Function
    Properties:
      # TODO Cloudwatch Event trigger here
      Environment:
        Variables:
          RECORD_TYPE: holdings
          RECORD_FIELDS: id,bibIds,bibIdLinks,itemIds,itemIdLinks,inheritLocation,allocationRule,accountingUnit,labelCode,serialCode1,serialCode2,serialCode3,serialCode4,claimOnDate,receivingLocationCode,vendorCode,updateCount,pieceCount,eCheckInCode,mediaTypeCode,updatedDate,createdDate,deletedDate,deleted,suppressed,fixedFields,varFields
          SCHEMA_TYPE: SierraHolding
          KINESIS_STREAM: SierraHoldingParser-qa
